/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.example.babydiarycompose.models


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param id 
 * @param username 
 * @param firstName 
 * @param lastName 
 * @param email 
 * @param password 
 * @param phone 
 * @param userStatus User Status
 */
@Serializable

data class User (

    @SerialName(value = "id")
    val id: kotlin.Long? = null,

    @SerialName(value = "user_name")
    val username: kotlin.String? = null,

    @SerialName(value = "first_name")
    val firstName: kotlin.String? = null,

    @SerialName(value = "last_name")
    val lastName: kotlin.String? = null,

    @SerialName(value = "email")
    val email: kotlin.String? = null,

    @SerialName(value = "password")
    val password: kotlin.String? = null,

    @SerialName(value = "phone")
    val phone: kotlin.String? = null,

    /* User Status */
    @SerialName(value = "user_status")
    val userStatus: kotlin.Int? = null

)

